mv en/markup_operations_bar.png .
mv en/markup_operations_parser.png .
mv en/parser_01.jpg .
mv en/markup_abrir_programa.jpg .
mv en/parser_openFile.jpg .
mv en/parser_openFile2.jpg .
mv en/parser_openFile3.jpg .
mv en/parser_openFile4.jpg .
mv en/parser_config.jpg .
mv en/parser_config1.jpg .
mv en/parser_parse.jpg .
mv en/parser_noerror.jpg .
mv en/parser_error1.jpg .
