mv en/markup_file_system.png .
mv en/markup_open.jpg .
mv en/markup_word_path.jpg .
mv en/markup_2007_habilitar_macros.jpg .
mv en/markup_botao_markup.jpg .
mv en/markup_2007_botao_suplementos.jpg .
mv en/markup_habilitarmacro.jpg .
mv en/markup_habilitarmacro2.jpg .
mv en/markup_barras.jpg .
mv en/markup_2007_posicao_das_barras.jpg .
mv en/markup_operations_bar.png .
mv en/markup_operations_bar.png .
mv en/markup_exit_message.png .
mv en/markup_operations_bar_edit.png .
mv en/markup_operations_bar_del.png .
mv en/markup_operations_bar_save.png .
mv en/automata1.png .
mv en/automata1b.jpg .
mv en/automata2.png .
mv en/markup_automata2_select.jpg .
mv en/markup_main_bar_auto2.JPG .
mv en/markup_automata2_marcado.jpg .
mv en/automata3.png .
mv en/automata3.png .
mv en/automata1b.jpg .
mv en/markup_operations_bar.png .
mv en/markup_operations_parser.png .
mv en/markup_main_bar_parser.JPG .
mv en/markup_operations_xml.png .
mv en/markup_operations_xml_style_report.png .
mv en/markup_operations_data_val_report.png .
mv en/markup_operations_pmc_style_report.png .
mv en/markup_bar_floating.png .
mv en/markup_inicial.jpg .
mv en/markup_barra_hierarquica2.jpg .
mv en/markup_barra_front.jpg .
mv en/markup_barra_titlegrp.jpg .
mv en/markup_barra_title.jpg .
mv en/markup_barra_title_sobe.jpg .
mv en/markup_barra_titlegrp_paracima.jpg .
mv en/markup_barra_front_0.jpg .
mv en/markup_msg_invalid_value_for_attribute.jpg .
mv en/markup_msg_inserting_tag.png .
mv en/markup_msg_inserting_tag.jpg .
mv en/markup_msg_inserting_tag_03.png .
mv en/markup_msg_select_text.jpg .
